version: '3'
services:
  web-blue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  web-green:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
