name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, docker-server]

    steps:
    # Stap 1: Checkout de code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Stap 2: Log in op Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

    # Stap 3: Bouw de Docker-image
    - name: Build the Docker image
      run: docker build -t stijn0vp/website:latest .

    # Stap 4: Push de Docker-image naar Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push stijn0vp/website:latest

    # Stap 5: Bepaal welke container het langst draait en vervang deze
    - name: Determine longest running container
      id: env
      run: |
        # Controleer of de containers bestaan
        if docker ps -a --format '{{.Names}}' | grep -Eq "^website-blue$"; then
          blue_started=$(docker inspect -f '{{ .State.StartedAt }}' website-blue)
        else
          blue_started="none"
        fi
        
        if docker ps -a --format '{{.Names}}' | grep -Eq "^website-green$"; then
          green_started=$(docker inspect -f '{{ .State.StartedAt }}' website-green)
        else
          green_started="none"
        fi

        # Bepaal welke container moet worden vervangen
        if [ "$blue_started" = "none" ]; then
          echo "env=blue" >> $GITHUB_ENV
        elif [ "$green_started" = "none" ]; then
          echo "env=green" >> $GITHUB_ENV
        elif [ "$blue_started" \< "$green_started" ]; then
          echo "env=blue" >> $GITHUB_ENV
        else
          echo "env=green" >> $GITHUB_ENV

    # Stap 6: Vervang de container die het langst draaide
    - name: Deploy to Docker container
      run: |
        docker pull stijn0vp/website:latest
        docker stop website-${{ env.env }} || true
        docker rm website-${{ env.env }} || true

        if [ "${{ env.env }}" = "blue" ]; then
          docker run -d -p 8080:80 --name website-blue stijn0vp/website:latest
        else
          docker run -d -p 8081:80 --name website-green stijn0vp/website:latest
