name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Pas dit aan naar de branch die je wilt gebruiken

jobs:
  build:
    runs-on: [self-hosted, docker-server]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t stijn0vp/website:latest .

    - name: Push the Docker image to Docker Hub
      run: docker push stijn0vp/website:latest

    - name: Deploy container
      run: |
        docker pull stijn0vp/website:latest
        
        # Check if both containers exist
        BLUE_EXISTS=$(docker ps -a --filter "name=blue" --format "{{.Names}}")
        GREEN_EXISTS=$(docker ps -a --filter "name=green" --format "{{.Names}}")

        if [ -z "$BLUE_EXISTS" ] && [ -z "$GREEN_EXISTS" ]; then                          # If neither container exists, deploy blue
          docker run -d -p 8081:80 --name blue stijn0vp/website:latest
        elif [ -z "$BLUE_EXISTS" ]; then                                                  # If only blue doesn't exist, deploy blue
          docker run -d -p 8081:80 --name blue stijn0vp/website:latest
        elif [ -z "$GREEN_EXISTS" ]; then                                                 # If only green doesn't exist, deploy green
          docker run -d -p 8082:80 --name green stijn0vp/website:latest
        else                                                                          # If both containers exist, check which one has been running longer and replace the other
          BLUE_UPTIME=$(docker inspect -f '{{.State.StartedAt}}' blue)
          GREEN_UPTIME=$(docker inspect -f '{{.State.StartedAt}}' green)

          if [ "$BLUE_UPTIME" \< "$GREEN_UPTIME" ]; then                        # If blue has been running longer, replace blue
            docker stop blue
            docker rm blue
            docker run -d -p 8081:80 --name blue stijn0vp/website:latest
          else                                                                  # If green has been running longer, replace green
            docker stop green
            docker rm green
            docker run -d -p 8082:80 --name green stijn0vp/website:latest
          fi
        fi

  approval:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: stijnvandepol

  update-haproxy:
    runs-on: [self-hosted, haproxy-server]
    needs: approval
    if: success()

    steps:
    - name: Switch proxy
      run: |
        echo "Running switchconfig.sh..."
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S bash /home/student/switchconfig.sh 2>&1
        echo "switchconfig.sh executed successfully."

    - name: Remove old container
      run: |
        # Check if old container exists and remove it
        BLUE_OLD_EXISTS=$(docker ps -a --filter "name=blue_old" --format "{{.Names}}")
        GREEN_OLD_EXISTS=$(docker ps -a --filter "name=green_old" --format "{{.Names}}")

        if [ -n "$BLUE_OLD_EXISTS" ]; then
          docker rm blue_old
        elif [ -n "$GREEN_OLD_EXISTS" ]; then
          docker rm green_old
        fi

  rollback:
    runs-on: [self-hosted, docker-server]
    needs: approval
    if: failure()  # Voer deze job alleen uit als de goedkeuring wordt geweigerd

    steps:
    - name: Rollback deployment
      run: |
        # Check which container was running before the new deployment
        BLUE_OLD_EXISTS=$(docker ps -a --filter "name=blue_old" --format "{{.Names}}")
        GREEN_OLD_EXISTS=$(docker ps -a --filter "name=green_old" --format "{{.Names}}")

        if [ -n "$BLUE_OLD_EXISTS" ]; then
          docker stop blue
          docker rm blue
          docker rename blue_old blue                                               # Herstel blue_old naar blue
          docker start blue
        elif [ -n "$GREEN_OLD_EXISTS" ]; then
          docker stop green
          docker rm green
          docker rename green_old green                                             # Herstel green_old naar green
          docker start green
        fi
