name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Pas dit aan naar de branch die je wilt gebruiken

jobs:
  build:
    runs-on: [self-hosted, docker-server]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t stijn0vp/website:latest .

    - name: Push the Docker image to Docker Hub
      run: docker push stijn0vp/website:latest

    - name: Deploy container
      run: |
        # Check if both containers exist
        BLUE_EXISTS=$(docker ps -a --filter "name=blue" --format "{{.Names}}")
        GREEN_EXISTS=$(docker ps -a --filter "name=green" --format "{{.Names}}")

        if [ -z "$BLUE_EXISTS" ] && [ -z "$GREEN_EXISTS" ]; then                    # Als beide containers niet bestaan, deploy blue
          docker run -d -p 8081:80 --name blue stijn0vp/website:latest
        elif [ -z "$BLUE_EXISTS" ]; then                                            # Als blue niet bestaat, deploy blue en bewaar green
          docker rename green green_old
          docker run -d -p 8081:80 --name blue stijn0vp/website:latest
        elif [ -z "$GREEN_EXISTS" ]; then                                           # Als green niet bestaat, deploy green en bewaar blue
          docker rename blue blue_old
          docker run -d -p 8082:80 --name green stijn0vp/website:latest
        else
          BLUE_UPTIME=$(docker inspect -f '{{.State.StartedAt}}' blue)
          GREEN_UPTIME=$(docker inspect -f '{{.State.StartedAt}}' green)
          if [ "$BLUE_UPTIME" \< "$GREEN_UPTIME" ]; then
            docker stop blue
            docker rename blue blue_old                                           # Bewaar de oude container
            docker run -d -p 8081:80 --name blue stijn0vp/website:latest
          else
            docker stop green
            docker rename green green_old                                         # Bewaar de oude container
            docker run -d -p 8082:80 --name green stijn0vp/website:latest
          fi
        fi

  approval:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Manual approval                              # Voeg een goedkeuring toe voordat de volgende jobs worden uitgevoerd                     
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: stijnvandepol

  update-haproxy:
    runs-on: [self-hosted, haproxy-server]
    needs: approval
    if: success()                                       # Voer deze job alleen uit als de goedkeuring is gegeven

    steps:
    - name: Switch proxy
      run: |
        echo "Running switchconfig.sh..."
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S bash /home/student/switchconfig.sh 2>&1
        echo "switchconfig.sh executed successfully."

    - name: Remove old container
      run: |
        # Verwijder de oude container na succesvolle switch
        OLD_CONTAINER=$(docker ps -a --filter "name=blue_old" --format "{{.Names}}")
        if [ -n "$OLD_CONTAINER" ]; then
          docker rm blue_old
        else
          OLD_CONTAINER=$(docker ps -a --filter "name=green_old" --format "{{.Names}}")
          if [ -n "$OLD_CONTAINER" ]; then
            docker rm green_old
          fi
        fi

  rollback:
    runs-on: [self-hosted, docker-server]
    needs: approval
    if: failure()  # Voer deze job alleen uit als de goedkeuring wordt geweigerd

    steps:
    - name: Rollback deployment
      run: |
        # Stop de nieuwe container en herstart de oude
        NEW_CONTAINER=$(docker ps --filter "name=blue" --format "{{.Names}}")
        if [ -z "$NEW_CONTAINER" ]; then
          docker stop green
          docker rm green
          docker rename green_old green
          docker start green
        else
          docker stop blue
          docker rm blue
          docker rename blue_old blue
          docker start blue
        fi

    - name: Remove old container
      run: |
        # Verwijder de oude container na rollback
        OLD_CONTAINER=$(docker ps -a --filter "name=blue_old" --format "{{.Names}}")
        if [ -n "$OLD_CONTAINER" ]; then
          docker rm blue_old
        else
          OLD_CONTAINER=$(docker ps -a --filter "name=green_old" --format "{{.Names}}")
          if [ -n "$OLD_CONTAINER" ]; then
            docker rm green_old
          fi
        fi
