name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Pas dit aan naar de branch die je wilt gebruiken

jobs:
  build:
    runs-on: [self-hosted, docker-server]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t stijn0vp/website:latest .

    - name: Push the Docker image to Docker Hub
      run: docker push stijn0vp/website:latest

    - name: Deploy container
      run: |
        docker pull stijn0vp/website:latest
        
        # Check if both containers exist
        BLUE_EXISTS=$(docker ps -a --filter "name=blue" --format "{{.Names}}")
        GREEN_EXISTS=$(docker ps -a --filter "name=green" --format "{{.Names}}")

        if [ -z "$BLUE_EXISTS" ] && [ -z "$GREEN_EXISTS" ]; then                    # Als beide containers niet bestaan, deploy blue
          docker run -d -p 8081:80 --name blue stijn0vp/website:latest
        elif [ -z "$BLUE_EXISTS" ]; then                                            # Als blue niet bestaat, deploy blue
          docker run -d -p 8081:80 --name blue stijn0vp/website:latest
        elif [ -z "$GREEN_EXISTS" ]; then                                           # Als green niet bestaat, deploy green
          docker run -d -p 8082:80 --name green stijn0vp/website:latest
        else
          BLUE_UPTIME=$(docker inspect -f '{{.State.StartedAt}}' blue 2>/dev/null || echo "")
          GREEN_UPTIME=$(docker inspect -f '{{.State.StartedAt}}' green 2>/dev/null || echo "")

          if [ -n "$BLUE_UPTIME" ] && [ -n "$GREEN_UPTIME" ]; then                  # Als beide containers bestaan, bepaal de oudste en hernoem
            if [ "$BLUE_UPTIME" \< "$GREEN_UPTIME" ]; then
              docker stop blue || true
              docker rm blue || true
              docker run -d -p 8081:80 --name blue stijn0vp/website:latest
            else
              docker stop green || true
              docker rm green || true
              docker run -d -p 8082:80 --name green stijn0vp/website:latest
            fi
          else
            echo "Error: One of the containers could not be inspected"
          fi
        fi


  approval:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: stijnvandepol

  update-haproxy:
    runs-on: [self-hosted, haproxy-server]
    needs: approval
    if: success()

    steps:
    - name: Switch proxy
      run: |
        echo "Running switchconfig.sh..."
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S bash /home/student/switchconfig.sh 2>&1
        echo "switchconfig.sh executed successfully."

  remove-old-container:
    runs-on: [self-hosted, docker-server]
    needs: update-haproxy  # Deze job draait na het succesvol uitvoeren van update-haproxy

    steps:
    - name: Remove old container
      run: |
        BLUE_OLD_EXISTS=$(docker ps -a --filter "name=blue_old" --format "{{.Names}}")
        GREEN_OLD_EXISTS=$(docker ps -a --filter "name=green_old" --format "{{.Names}}")

        if [ -n "$BLUE_OLD_EXISTS" ]; then
          docker rm blue_old || echo "No blue_old container to remove"
        elif [ -n "$GREEN_OLD_EXISTS" ]; then
          docker rm green_old || echo "No green_old container to remove"
        fi


  rollback:
    runs-on: [self-hosted, docker-server]
    needs: approval
    if: failure()  # Voer deze job alleen uit als de goedkeuring wordt geweigerd

    steps:
    - name: Rollback deployment
      run: |
        # Check which container was running before the new deployment
        BLUE_OLD_EXISTS=$(docker ps -a --filter "name=blue_old" --format "{{.Names}}")
        GREEN_OLD_EXISTS=$(docker ps -a --filter "name=green_old" --format "{{.Names}}")

        if [ -n "$BLUE_OLD_EXISTS" ]; then
          docker stop blue || echo "No blue container running"
          docker rm blue || echo "No blue container to remove"
          docker rename blue_old blue
          docker start blue
        elif [ -n "$GREEN_OLD_EXISTS" ]; then
          docker stop green || echo "No green container running"
          docker rm green || echo "No green container to remove"
          docker rename green_old green
          docker start green
        fi

