name: Build and Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: app.Dockerfile 
          tags: ghcr.io/jamie-mh/zerodowndeploy:latest,ghcr.io/jamie-mh/zerodowndeploy:${{ github.ref_name }}

      - name: Build and push Caddy image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: caddy.Dockerfile
          tags: ghcr.io/jamie-mh/zerodowndeploy-caddy:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy.key
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/deploy.key

          cat >>~/.ssh/config <<END
          Host remote
              HostName ${{ secrets.DEPLOY_HOST }}
              User deploy
              IdentityFile ~/.ssh/deploy.key
              StrictHostKeyChecking no
              ControlMaster auto
              ControlPath ~/.ssh/control-%C
              ControlPersist yes
          END

      - name: Deploy
        run: |
          export DOCKER_HOST=ssh://remote
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Deploy current tag
          sed -i 's/zerodowndeploy:latest/zerodowndeploy:${{ github.ref_name }}/' compose.yaml   

          docker compose pull
          docker compose up -d --no-recreate

          # Route traffic to the Green instance
          # Verander deze sectie met je routing script
          # (Het script moet dynamisch de configuratie van Caddy aanpassen)

          # Restart de Blue en Green containers
          # Wacht tot containers gezond zijn

          # Schoon oude images op
