name: Deploy to Test and Production

on:
  push:
    branches:
      - main  # Pas dit aan naar jouw werkbranch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build -t test ./test
          docker build -t production ./prod

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push test
          docker push production

      - name: Deploy to Test
        run: |
          docker-compose -f docker-compose.yml up -d test

      - name: Manual Approval for Production
        run: |
          echo "Please verify the test environment and then run the command to switch to production."

      - name: Switch to Production
        if: github.event.action == 'approve'
        run: |
          # Commando om om te schakelen naar de productie-container
          docker-compose -f docker-compose.yml up -d production
