name: Build and Push Docker images

on:
  push:
    branches:
      - main  # Of een andere branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build blue image
        run: |
          docker build -t website:blue ./blue

      - name: Build green image
        run: |
          docker build -t website:green ./green

      - name: Push blue image
        run: |
          docker push website:blue

      - name: Push green image
        run: |
          docker push website:green
