name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Pas dit aan naar jouw hoofdtak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t jouw-website:latest  # Vervang dit door jouw image naam

    - name: Push Docker image
      run: docker push jouw-website:latest  # Vervang dit door jouw image naam
